- name: "Acao de resultados"
  hosts: all
  vars:
    results_dir_effective: "{{ user_dir }}/output/cluster-{{ ansible_play_hosts | length }}"
  gather_facts: true
  tasks:
  - name: "Task 1: Lista as variáveis recebidas"
    debug:
      msg: "Variaveis: results_dir: {{ results_dir }}; user_dir: {{ user_dir }}"

  - name: "Task 2: Copia os arquivos output-*.txt"
    fetch:
      src: "{{ results_dir_effective }}/output-{{ node_rank }}.txt"
      dest: "./../../../results/cluster-{{ ansible_play_hosts | length }}"
